<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h5_Log in</name>
   <tag></tag>
   <elementGuidId>734fafad-38d3-4e38-931b-f63f0065d642</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#logInModalLabel</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h5[@id='logInModalLabel']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h5</value>
      <webElementGuid>1be7aa3f-bde9-4742-b468-94bcdce32ae3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-title</value>
      <webElementGuid>cebd49a4-b439-427c-b54b-c9061f3754c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>logInModalLabel</value>
      <webElementGuid>2c378939-8b5d-46f4-ba27-b3e5118262a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Log in</value>
      <webElementGuid>e69ce7ef-b5ab-4494-861e-f8fa4e3e6087</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;logInModalLabel&quot;)</value>
      <webElementGuid>45996d88-e35f-4d80-8ce2-097321629c32</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h5[@id='logInModalLabel']</value>
      <webElementGuid>792fe0a5-612f-4882-98e1-7d0625f3ab7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='logInModal']/div/div/div/h5</value>
      <webElementGuid>361615ff-6082-4f84-9f1b-632fb37f06d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/h5</value>
      <webElementGuid>005b1572-8eff-4885-8cc6-d0aa02d71bf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h5[@id = 'logInModalLabel' and (text() = 'Log in' or . = 'Log in')]</value>
      <webElementGuid>d35e68b1-0109-4fcd-93a8-d58e2c00a6d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
